app = "itadoritrue"
primary_region = "gru"

[build]
dockerfile = "Dockerfile"

[env]
NODE_ENV = "production"
PORT = "8080"
DATA_DIR = "/data"

[http_service]
internal_port = 8080
force_https = true
auto_start_machines = false
auto_stop_machines = "off"
processes = ["app"]

[[mounts]]
source = "data"
destination = "/data"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
